# src/analyze_logs.py
"""
Analyze simulation logs and generate:
  - basic stats (num steps, attacks, safety actions)
  - attack timeline plot
  - attack type frequency bar chart
  - safety action frequency bar chart

Run from project root:
    python -m src.analyze_logs

Make sure you have at least one CSV in logs/ generated by main.py.
"""

import os
import glob

import matplotlib.pyplot as plt
import pandas as pd


LOG_DIR = "logs"
REPORTS_DIR = "reports"


def get_latest_log_path() -> str:
    """Return path to the most recent log file in logs/."""
    pattern = os.path.join(LOG_DIR, "simulation_run_*.csv")
    files = glob.glob(pattern)
    if not files:
        raise FileNotFoundError(
            f"No log files found in {LOG_DIR}/. Run `python -m src.main` first."
        )
    files.sort()  # lexicographic sort, timestamp is in name
    return files[-1]


def basic_stats(df: pd.DataFrame) -> None:
    """Print basic statistics about the run."""
    num_steps = len(df)
    num_attacks = (df["ids_status"] == "ATTACK").sum()
    num_normal = num_steps - num_attacks

    print("\n=== BASIC STATS ===")
    print(f"Total steps         : {num_steps}")
    print(f"Normal steps        : {num_normal}")
    print(f"Attack steps        : {num_attacks}")
    print(f"Attack ratio        : {num_attacks / num_steps:.3f}")

    if "attack_type" in df.columns:
        print("\nAttack type distribution:")
        print(df["attack_type"].replace("", "NONE").value_counts())

    if "safety_action" in df.columns:
        print("\nSafety action distribution:")
        print(df["safety_action"].value_counts())


def plot_attack_timeline(df: pd.DataFrame, out_path: str) -> None:
    """
    Plot attack vs normal over time (step index).
    1 for attack, 0 for normal.
    """
    # create a numeric series: 1 if ATTACK else 0
    attack_flag = (df["ids_status"] == "ATTACK").astype(int)

    fig, ax = plt.subplots(figsize=(8, 3))
    ax.plot(df["step"], attack_flag, linestyle="-", marker="", linewidth=1)

    ax.set_xlabel("Step")
    ax.set_ylabel("Attack (1) / Normal (0)")
    ax.set_title("Attack Timeline")

    plt.tight_layout()
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    plt.savefig(out_path, dpi=200)
    plt.close(fig)


def plot_attack_type_counts(df: pd.DataFrame, out_path: str) -> None:
    """
    Bar chart of counts per attack_type (including NONE).
    """
    series = df["attack_type"].replace("", "NONE")
    counts = series.value_counts()

    fig, ax = plt.subplots(figsize=(6, 4))
    ax.bar(counts.index.astype(str), counts.values)

    ax.set_xlabel("Attack Type")
    ax.set_ylabel("Count")
    ax.set_title("Attack Type Frequency")

    plt.tight_layout()
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    plt.savefig(out_path, dpi=200)
    plt.close(fig)


def plot_safety_actions(df: pd.DataFrame, out_path: str) -> None:
    """
    Bar chart of how often each safety action is used.
    """
    counts = df["safety_action"].value_counts()

    fig, ax = plt.subplots(figsize=(6, 4))
    ax.bar(counts.index.astype(str), counts.values)

    ax.set_xlabel("Safety Action")
    ax.set_ylabel("Count")
    ax.set_title("Safety Action Usage")

    plt.tight_layout()
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    plt.savefig(out_path, dpi=200)
    plt.close(fig)


def main() -> None:
    latest_log = get_latest_log_path()
    print(f"[*] Using latest log file: {latest_log}")

    df = pd.read_csv(latest_log)

    # Basic printable stats
    basic_stats(df)

    # Plots
    os.makedirs(REPORTS_DIR, exist_ok=True)
    timeline_path = os.path.join(REPORTS_DIR, "attack_timeline.png")
    attack_type_path = os.path.join(REPORTS_DIR, "attack_type_counts.png")
    safety_path = os.path.join(REPORTS_DIR, "safety_action_counts.png")

    print("\n[*] Generating plots...")
    plot_attack_timeline(df, timeline_path)
    print(f"Saved attack timeline plot to     : {timeline_path}")

    plot_attack_type_counts(df, attack_type_path)
    print(f"Saved attack type counts plot to  : {attack_type_path}")

    plot_safety_actions(df, safety_path)
    print(f"Saved safety action counts plot to: {safety_path}")


if __name__ == "__main__":
    main()
