# src/analyze_trust.py
"""
Analyze trust evolution over time from simulation logs.

Requires:
  - logs generated by src.main (logger with trust columns)

This script:
  - finds the latest simulation_run_*.csv in logs/
  - loads it with pandas
  - prints some basic stats
  - plots:
      * trust vs step for each subsystem (ENGINE, STEERING, BRAKE)
      * attacks over time (as 0/1 line)
  - saves plots to reports/

Run from project root:
    python -m src.analyze_trust
"""

import glob
import os

import matplotlib.pyplot as plt
import pandas as pd

LOG_DIR = "logs"
REPORTS_DIR = "reports"


def get_latest_log_path() -> str:
    pattern = os.path.join(LOG_DIR, "simulation_run_*.csv")
    files = glob.glob(pattern)
    if not files:
        raise FileNotFoundError(
            f"No log files found in {LOG_DIR}/. Run `python -m src.main` first."
        )
    files.sort()
    return files[-1]


def basic_stats(df: pd.DataFrame) -> None:
    print("\n=== BASIC STATS ===")
    print(f"Total steps              : {len(df)}")
    if "ids_status" in df.columns:
        num_attacks = (df["ids_status"] == "ATTACK").sum()
        print(f"Attack steps             : {num_attacks}")
        print(f"Attack ratio             : {num_attacks / len(df):.3f}")

    if "attack_type" in df.columns:
        print("\nAttack type distribution:")
        print(df["attack_type"].replace("", "NONE").value_counts())

    print("\nTrust stats (min / max):")
    for col in ["engine_trust", "steering_trust", "brake_trust"]:
        if col in df.columns:
            print(
                f"  {col}: "
                f"min={df[col].min():.1f}, max={df[col].max():.1f}"
            )


def plot_trust_over_time(df: pd.DataFrame, out_path: str) -> None:
    """
    Plot ENGINE, STEERING, BRAKE trust vs step.
    """
    fig, ax = plt.subplots(figsize=(8, 4))

    ax.plot(df["step"], df["engine_trust"], label="ENGINE trust")
    ax.plot(df["step"], df["steering_trust"], label="STEERING trust")
    ax.plot(df["step"], df["brake_trust"], label="BRAKE trust")

    ax.set_xlabel("Step")
    ax.set_ylabel("Trust score (0–100)")
    ax.set_title("Subsystem Trust vs Time")
    ax.legend(loc="lower left")

    plt.tight_layout()
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    plt.savefig(out_path, dpi=200)
    plt.close(fig)


def plot_attacks_and_trust(df: pd.DataFrame, out_path: str) -> None:
    """
    Plot attacks over time (0/1) and one representative trust line (e.g. STEERING).
    This visually shows trust drops when attacks occur.
    """
    if "ids_status" not in df.columns:
        return

    attack_flag = (df["ids_status"] == "ATTACK").astype(int)

    fig, ax1 = plt.subplots(figsize=(8, 4))

    # Attack line (0/1)
    ax1.plot(df["step"], attack_flag, linewidth=1)
    ax1.set_xlabel("Step")
    ax1.set_ylabel("Attack (1)/Normal(0)")
    ax1.set_title("Attacks vs Steering Trust Over Time")

    # Secondary axis with steering trust if available
    if "steering_trust" in df.columns:
        ax2 = ax1.twinx()
        ax2.plot(df["step"], df["steering_trust"], linewidth=1)
        ax2.set_ylabel("STEERING trust (0–100)")

    plt.tight_layout()
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    plt.savefig(out_path, dpi=200)
    plt.close(fig)


def main() -> None:
    latest_log = get_latest_log_path()
    print(f"[*] Using latest log file: {latest_log}")

    df = pd.read_csv(latest_log)

    basic_stats(df)

    os.makedirs(REPORTS_DIR, exist_ok=True)
    trust_path = os.path.join(REPORTS_DIR, "trust_over_time.png")
    attack_trust_path = os.path.join(REPORTS_DIR, "attacks_vs_steering_trust.png")

    print("\n[*] Generating trust plots...")
    plot_trust_over_time(df, trust_path)
    print(f"Saved trust vs time plot to          : {trust_path}")

    plot_attacks_and_trust(df, attack_trust_path)
    print(f"Saved attacks vs steering trust plot : {attack_trust_path}")


if __name__ == "__main__":
    main()
